### ISSUE TITLE
Plans for a templating language?

### ISSUE THREAD

**Issue by matthewmueller** [rsms/ghp#1]
Hi @rsms, this is really cool.

I've also been thinking about ways to better serve frontends from Go to get back to a more traditional server-rendered architecture. The current state of affairs with node serving frontends adds a lot of complexity.

I noticed that right now the ServeHTTP just writes a string. That's probably the most flexible, but I'm wondering if there are any plans to go higher-level?  PHP allows you to fluidly include blocks of code in their HTML templates (for better or for worse haha)

I recently saw https://github.com/benbjohnson/ego#code-blocks as a possible way to do it. In practice, that looks like this: https://github.com/contribsys/faktory/blob/a751fb00ed3af1d9dc592dd9a8b724e468cb08e5/webui/queue.ego

Personally, it seems a bit messy to me in Go, so I've been thinking about ways to improve the syntax a bit and I'm wondering if you have too :-)

**Comment by rsms** [comment]
[`html/template`](https://golang.org/pkg/html/template/) is another option, used by for example [Hugo](https://gohugo.io/templates/introduction/)

**Comment by matthewmueller** [comment]
Ah yah, maybe that'll work just fine. I'm mostly looking for a better solution for having javascript "take it from here". It might be some subset of JS that works with Go and looks like JSX. This might work too: https://stimulusjs.org/

Otherwise, we'll just have to wait for better Go + WASM :D
